require:
  - rubocop-rails
  - rubocop-rspec
Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - node_modules/**/*
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
Style/WordArray:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
