version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - "3000:3000"
      - "3035:3035"
    command: bundle exec rails s -b 0.0.0.0
    env_file: .env
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules/:/app/node_modules
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    working_dir: /app
    depends_on:
     - db
    tty: true
volumes:
  db_data:
  bundle:
  node_modules:
