version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    image: rails_template_app
    ports:
      - "3000:3000"
      - "3035:3035"
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    env_file: .env
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules/:/app/node_modules
      - app_log:/app/log
      - app_tmp_cache:/app/tmp/cache
    working_dir: /app
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db_data:
  bundle:
  node_modules:
  app_log:
  app_tmp_cache:
