version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    image: rails_template_app
    ports:
      - "3000:3000"
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    env_file: .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
      - DEV_DOCKER=true
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules/:/app/node_modules
      - packs:/app/public/packs
      - app_log:/app/log
      - app_tmp_cache:/app/tmp/cache
    working_dir: /app
    depends_on:
      - db
      - webpack_dev_server
    tty: true
    stdin_open: true
  webpack_dev_server:
    image: rails_template_app
    ports:
      - "3035:3035"
    command: ./bin/webpack-dev-server
    env_file: .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - packs:/app/public/packs
      - node_modules/:/app/node_modules
    working_dir: /app
    tty: true
    stdin_open: true
  # cap:
    # build:
    #   context: .
    #   dockerfile: ./docker/cap/Dockerfile
    # image: cap
    # ports:
    #   - "10022:22"
    # depends_on:
    #   - db
    # tty: true
    # stdin_open: true
    # volumes:
    #   - cap_shared:/var/www/rails_template/shared
volumes:
  db_data:
  bundle:
  node_modules:
  packs:
  app_log:
  app_tmp_cache:
  # cap_shared:
