export const SET_LOADING = "SET_LOADING"
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE"
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE"

export const BASE_SET_LOADING = "base/SET_LOADING"
export const BASE_SET_ERROR_MESSAGE = "base/SET_ERROR_MESSAGE"
export const BASE_CLEAR_ERROR_MESSAGE = "base/CLEAR_ERROR_MESSAGE"
