name: ci

on: [push]

jobs:
  ci_rails:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_USER: pguser
      DB_PASSWORD: password
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Install bundler
      run: gem install bundler -v 2.0.1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install gem dependencies
      run: bundle install --path vendor/bundle --deployment --without production development
    - name: Install npm dependencies
      run: yarn install --production --frozen-lockfile
    # - name: Run assets precompile
    #   run: bundle exec rails assets:precompile RAILS_ENV=test
    - name: DB setup
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run Rspec
      run: bundle exec rspec
    - uses: actions/upload-artifact@v2
      with:
        name: coverage_rspec
        path: coverage/rspec
